version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  # 每台机子上 
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.1
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_HOST: localhost:9200