version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data


  elasticsearch:
    image: elasticsearch:7.3.1
    container_name: elasticsearch
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - transport.host=127.0.0.1
      - cluster.name=search
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.3.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_USER: elastic
      I18N_LOCALE: zh-CN
    depends_on: 
      - elasticsearch
      - logstash

  logstash:
    image: logstash:7.3.1
    container_name: logstash
    environment:
      ELASTICSEARCH_HOST: localhost:9200
      xpack.monitoring.enabled: "false"
    volumes: 
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      
    ports: 
      - 9600:9600
      - 5044:5044
    depends_on: 
      - elasticsearch

  # 每台机子上 
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.1
    container_name: filebeat
    environment:
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_HOST: localhost:9200
    depends_on: 
      - elasticsearch